### ISSUE TITLE
App crashed after call `ParticleWallet.navigatorDappBrowser`

### ISSUE THREAD

**Issue by lpylpyleo** [Particle-Network/particle-flutter#10]
version: 1.4.2
Have called init in main():
```dart
  ParticleWallet.init(
    WalletMetaData(
      "Particle Connect",
      "https://connect.particle.network/icons/512.png",
      "https://connect.particle.network",
      "Particle Connect Flutter Demo",
    ),
  );
``` 

<details>
<summary>
log
</summary>

<pre>
2024-01-02 22:36:36.513 18375-18375 AndroidRuntime 	D 	Shutting down VM
2024-01-02 22:36:36.514 18375-18375 AndroidRuntime 	E 	FATAL EXCEPTION: main
 	Process: com.read2n.android, PID: 18375
 	java.lang.RuntimeException: Unable to resume activity {com.read2n.android/com.particle.gui.ui.browser.DAppBrowserActivity}: java.lang.NullPointerException
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4774)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4807)
 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loopOnce(Looper.java:201)
 	at android.os.Looper.loop(Looper.java:288)
 	at android.app.ActivityThread.main(ActivityThread.java:7959)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
 	Caused by: java.lang.NullPointerException
 	at com.particle.gui.ParticleWallet.getWalletAddress(SourceFile:1)
 	at com.particle.gui.ui.browser.DAppBrowserFragment.onResume(SourceFile:2)
 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3189)
 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2911)
 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
 	at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:245)
 	at android.app.Activity.performResume(Activity.java:8505)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4764)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4807) 
 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57) 
 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179) 
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
 	at android.os.Handler.dispatchMessage(Handler.java:106) 
 	at android.os.Looper.loopOnce(Looper.java:201) 
 	at android.os.Looper.loop(Looper.java:288) 
 	at android.app.ActivityThread.main(ActivityThread.java:7959) 
 	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 
</pre>
</details>

**Comment by xxhong** [comment]
Requires successful login

**Comment by lpylpyleo** [comment]
This does not solve my problems and the issue should remain open.
I can confirm that I have logged in with particle auth.

And even if i haven't logged in, call this method shouldn't cause my app to crash.

**Comment by lpylpyleo** [comment]
@xxhong Any ideas?
