### ISSUE TITLE
`particle_connect`: `ParticleConnect.importPrivateKey` method call error.

### ISSUE THREAD

**Issue by Ce1ling** [Particle-Network/particle-flutter#7]
您好，

我在使用 `particle_connect` 时遇到了一些问题，我调用 `ParticleConnect.importPrivateKey` 或 `ParticleConnect.connect`，会得到这个错误：

```
Exception has occurred.
PlatformException (PlatformException(error, adapters can not be empty, null, java.lang.RuntimeException: adapters can not be empty
	at com.particle.connect.ParticleConnect.lazyCreateAdapters(SourceFile:7)
	at com.particle.connect.ParticleConnect.access$lazyCreateAdapters(SourceFile:1)
	at com.particle.connect.ParticleConnect$adapters$2.invoke(SourceFile:2)
	at com.particle.connect.ParticleConnect$adapters$2.invoke(SourceFile:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.particle.connect.ParticleConnect.getAdapters(SourceFile:1)
	at com.particle.connect.ParticleConnect.getAdapters(SourceFile:4)
	at network.particle.flutter.bridge.module.ConnectBridge.connect(ConnectBridge.kt:145)
	at network.particle.connect_plugin.particle_connect.ParticleConnectPlugin.onMethodCall(ParticleConnectPlugin.kt:62)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
))
```

不仅在我的 App 中会出现这个错误，我运行官方示例（`particle-wallet` 或 `particle-connect`）点击其中的 `Import Private Key` 和 `Connect` 按钮也会得到相同的错误。

**Comment by Ce1ling** [comment]
哦～我发现了错误，是我的问题。

**Comment by Ce1ling** [comment]
Oh~ I found the error; it was my issue.
